export const SET_LANG = 'SET_LANG';
export const SET_INTERNET_CONNECTION = 'SET_INTERNET_CONNECTION';
export const REFRESH_LIST = 'REFRESH_LIST';

export const SET_LOCATION = 'SET_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';
export const SET_GPS_STATUS = 'SET_GPS_STATUS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FB_FAIL = 'LOGIN_FB_FAIL';
export const LOGIN_RESET_ERROR = 'LOGIN_RESET_ERROR';
export const LOGOUT = 'LOGOUT';

export const SELECT_TAB = 'SELECT_TAB';
